version: '3.1'
services:
  server:
    container_name: express-proxy-pass-server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    ports:
      - 3000:3000